CREATE TABLE `courses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `slug` varchar(250) NOT NULL,
  `description` text NOT NULL,
  `category_id` int NOT NULL,
  `instructor_id` int NOT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `trailer_video_url` varchar(500) DEFAULT NULL,
  `level` enum('beginner','intermediate','advanced') NOT NULL,
  `duration` decimal(5,2) DEFAULT NULL,
  `language` enum('English','Français','Arabic') DEFAULT 'English',
  `requirements` json DEFAULT NULL,
  `learning_objectives` json DEFAULT NULL,
  `tags` json DEFAULT NULL,
  `rating` decimal(3,2) DEFAULT '0.00',
  `student_count` int DEFAULT '0',
  `is_certified` tinyint(1) DEFAULT '1',
  `last_updated` date DEFAULT NULL,
  `is_published` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `fk_courses_category` (`category_id`),
  KEY `fk_courses_instructor` (`instructor_id`),
  CONSTRAINT `fk_courses_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`),
  CONSTRAINT `fk_courses_instructor` FOREIGN KEY (`instructor_id`) REFERENCES `instructors` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
